package ru.kata.project.shared.kafka.consumer;

import lombok.extern.slf4j.Slf4j;
import org.apache.avro.generic.GenericRecord;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.support.KafkaHeaders;
import org.springframework.messaging.handler.annotation.Header;
import org.springframework.stereotype.Service;

/**
 * AnalyticsServiceConsumer
 * <p>
 * Consumer "analytics-service".
 * </p>
 * <p>
 * Агрегирует AI и job-события для анализа событий и отчётности.
 * </p>
 * <ul>
 *  <li> чтение из топиков "resume.lifecycle", "job.posting";</li>
 *  <li> Логи имеют отличия, исходя из прочитанного сообщения.</li>
 * </ul>
 *
 * @author Vladislav_Bogomolov
 */
@Slf4j
@Service
public class AnalyticsServiceConsumer {

    @KafkaListener(
            topics = {"resume.lifecycle", "job.posting"},
            groupId = "analytics-service-group"
    )
    public void handleAnalyticsEvent(GenericRecord record,
                                     @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
        try {
            final String eventType = getSafe(record, "eventType");
            final String eventId = getSafe(record, "eventId");
            final String traceId = getSafe(record, "traceId");

            log.info("📊 [AnalyticsService] Received event from topic='{}' → type='{}', eventId='{}', traceId='{}'",
                    topic, eventType, eventId, traceId);

            switch (eventType) {
                case "ResumeGenerated" -> handleResumeGenerated(record);
                case "ResumeAnalyzed" -> handleResumeAnalyzed(record);

                case "JobPublished" -> handleJobPublished(record);
                case "ApplicationStatusChanged" -> handleApplicationStatusChanged(record);

                default -> log.warn("⚠️ [AnalyticsService] Unknown event type '{}' from topic '{}'", eventType, topic);
            }
        } catch (Exception e) {
            log.error("❌ [AnalyticsService] Failed to process message from topic='{}': {}", topic, e.getMessage(), e);
        }
    }

    private void handleResumeGenerated(GenericRecord record) {
        final String title = getSafe(record, "title");
        final String source = getSafe(record, "source");
        log.info("📄 ResumeGenerated → Resume '{}' generated by '{}'", title, source);
    }

    private void handleResumeAnalyzed(GenericRecord record) {
        final String aggregateId = getSafe(record, "aggregateId");
        final String source = getSafe(record, "source");
        log.info("🧠 ResumeAnalyzed → Resume aggregateId='{}' analyzed by '{}'", aggregateId, source);
    }

    private void handleJobPublished(GenericRecord record) {
        log.info("💼 JobPublished → Placeholder handler (future event)");
    }

    private void handleApplicationStatusChanged(GenericRecord record) {
        log.info("📨 ApplicationStatusChanged → Placeholder handler (future event)");
    }

    private String getSafe(GenericRecord record, String field) {
        final Object value = record.get(field);
        if (value != null) {
            return value.toString();
        }
        return "N/A";
    }
}